import React, { useEffect, useState } from 'react';
import { 
  XAxis, YAxis, CartesianGrid, Tooltip, ResponsiveContainer, 
  AreaChart, Area, BarChart, Bar, Cell 
} from 'recharts';
import apiClient from '../api/client';
import { Brain, ShieldAlert, History, FileDown } from 'lucide-react';
import jsPDF from 'jspdf';
import autoTable from 'jspdf-autotable';

interface MoodLog {
  id: string;
  user_text: string;
  risk_level: string;
  confidence_score: number;
  emotion: string;
  ai_response: string;
  created_at: string;
}

const RISK_MAP: { [key: string]: number } = { low: 1, medium: 2, high: 3 };
const EMOTION_COLORS: { [key: string]: string } = {
  joy: '#10b981',
  sadness: '#3b82f6',
  fear: '#f59e0b',
  anger: '#ef4444',
  surprise: '#8b5cf6',
  love: '#ec4899'
};

export const Dashboard: React.FC = () => {
  const [logs, setLogs] = useState<MoodLog[]>([]);
  const [loading, setLoading] = useState(true);

  useEffect(() => {
    const fetchHistory = async () => {
      try {
        const response = await apiClient.get('/moods/');
        setLogs(response.data); 
      } catch (err) {
        console.error('Failed to fetch mood history', err);
      } finally {
        setLoading(false);
      }
    };
    fetchHistory();
  }, []);

  const reverseLogs = [...logs].reverse();
  const chartData = reverseLogs.map(log => ({
    date: new Date(log.created_at).toLocaleDateString(),
    risk: RISK_MAP[log.risk_level.toLowerCase()] || 1,
    confidence: log.confidence_score * 100,
    emotion: log.emotion
  }));

  const emotionCounts = logs.reduce((acc: any, log) => {
    const e = log.emotion.toLowerCase();
    acc[e] = (acc[e] || 0) + 1;
    return acc;
  }, {});

  const barData = Object.keys(emotionCounts).map(name => ({
    name: name.toUpperCase(),
    value: emotionCounts[name]
  }));

  const exportPDF = () => {
    try {
      const doc = new jsPDF();
      const timestamp = new Date().toLocaleString();

      // 1. Header
      doc.setFontSize(22);
      doc.setTextColor(59, 130, 246);
      doc.text('Sentimental AI: Clinical Journey Report', 14, 20);
      
      doc.setFontSize(10);
      doc.setTextColor(100);
      doc.text(`Generated on: ${timestamp}`, 14, 28);
      doc.text('This report summarizes emotional trends and AI-assisted mental health tracking.', 14, 33);

      // 2. Statistics Summary
      doc.setFontSize(16);
      doc.setTextColor(0);
      doc.text('Summary Statistics', 14, 45);
      
      const commonEmotion = barData.length > 0 ? barData.reduce((a, b) => a.value > b.value ? a : b).name : 'N/A';
      const recentRisk = logs.length > 0 ? logs[0].risk_level.toUpperCase() : 'N/A';

      autoTable(doc, {
        startY: 50,
        head: [['Metric', 'Value']],
        body: [
          ['Total Session Entries', logs.length.toString()],
          ['Dominant Emotional State', commonEmotion],
          ['Most Recent Risk Assessment', recentRisk],
        ],
        theme: 'striped',
        headStyles: { fillColor: [59, 130, 246] }
      });

      // 3. History Table
      const nextY = (doc as any).lastAutoTable.finalY + 15;
      doc.setFontSize(16);
      doc.text('Detailed Session History', 14, nextY);
      
      const tableData = logs.map(log => [
        new Date(log.created_at).toLocaleDateString(),
        log.emotion.toUpperCase(),
        log.risk_level.toUpperCase(),
        log.user_text.substring(0, 50) + (log.user_text.length > 50 ? '...' : '')
      ]);

      autoTable(doc, {
        startY: nextY + 5,
        head: [['Date', 'Emotion', 'Risk', 'Input Snippet']],
        body: tableData,
        theme: 'grid',
        headStyles: { fillColor: [31, 41, 55] },
        styles: { fontSize: 9 }
      });

      // 4. Disclaimer
      const finalY = (doc as any).lastAutoTable.finalY + 20;
      doc.setFontSize(8);
      doc.setTextColor(150);
      const disclaimer = "DISCLAIMER: This report is generated by an Artificial Intelligence system for informational purposes only. It is not a clinical diagnosis or medical advice. Please share this data with a licensed mental health professional for proper evaluation.";
      doc.text(disclaimer, 14, finalY, { maxWidth: 180 });

      doc.save('Sentimental_AI_Clinical_Report.pdf');
    } catch (error) {
      console.error('PDF Generation failed', error);
      alert('Failed to generate PDF. Please try again.');
    }
  };

  if (loading) return <div className="spinner-container"><div className="spinner"></div></div>;

  if (logs.length === 0) {
    return (
      <div className="empty-chat" style={{ padding: '4rem', textAlign: 'center' }}>
        <History size={48} color="#3b82f6" />
        <h3>No journey data yet.</h3>
        <p>Start chatting with the AI to see your emotional trends here!</p>
      </div>
    );
  }

  return (
    <div className="dashboard-container fade-in">
      <div className="dashboard-header-row">
        <div className="stats-title">
          <h3>Mental Health Analytics</h3>
          <p className="chart-sub">Overview of your emotional journey and risk assessments.</p>
        </div>
        <button onClick={exportPDF} className="export-btn">
          <FileDown size={18} />
          <span>Export Clinical PDF</span>
        </button>
      </div>

      <div className="stats-grid">
        <div className="stat-card">
          <History className="stat-icon blue" />
          <div className="stat-content">
            <span className="stat-label">Total Entries</span>
            <span className="stat-value">{logs.length}</span>
          </div>
        </div>
        <div className="stat-card">
          <Brain className="stat-icon green" />
          <div className="stat-content">
            <span className="stat-label">Common Emotion</span>
            <span className="stat-value">
              {barData.length > 0 ? barData.reduce((a, b) => a.value > b.value ? a : b).name : 'N/A'}
            </span>
          </div>
        </div>
        <div className="stat-card">
          <ShieldAlert className="stat-icon red" />
          <div className="stat-content">
            <span className="stat-label">Recent Risk</span>
            <span className="stat-value">
              {logs.length > 0 ? logs[0].risk_level.toUpperCase() : 'N/A'}
            </span>
          </div>
        </div>
      </div>

      <div className="charts-grid">
        <div className="chart-wrapper">
          <h3>Mental Health Risk Trend</h3>
          <p className="chart-sub">1: Low, 2: Medium, 3: High</p>
          <div style={{ width: '100%', height: '250px' }}>
            <ResponsiveContainer width="100%" height="100%">
              <AreaChart data={chartData} margin={{ top: 10, right: 10, left: -20, bottom: 0 }}>
                <defs>
                  <linearGradient id="colorRisk" x1="0" y1="0" x2="0" y2="1">
                    <stop offset="5%" stopColor="#3b82f6" stopOpacity={0.8}/>
                    <stop offset="95%" stopColor="#3b82f6" stopOpacity={0}/>
                  </linearGradient>
                </defs>
                <CartesianGrid strokeDasharray="3 3" vertical={false} stroke="#e2e8f0" />
                <XAxis dataKey="date" hide={chartData.length > 10} />
                <YAxis ticks={[1, 2, 3]} domain={[0, 4]} stroke="#64748b" />
                <Tooltip 
                  contentStyle={{ borderRadius: '12px', border: 'none', boxShadow: '0 10px 15px -3px rgba(0,0,0,0.1)' }}
                />
                <Area 
                  type="monotone" 
                  dataKey="risk" 
                  stroke="#3b82f6" 
                  strokeWidth={3}
                  fillOpacity={1} 
                  fill="url(#colorRisk)" 
                />
              </AreaChart>
            </ResponsiveContainer>
          </div>
        </div>

        <div className="chart-wrapper">
          <h3>Emotional Distribution</h3>
          <p className="chart-sub">Frequency of detected emotions</p>
          <div style={{ width: '100%', height: '250px' }}>
            <ResponsiveContainer width="100%" height="100%">
              <BarChart data={barData} margin={{ top: 10, right: 10, left: -20, bottom: 0 }}>
                <CartesianGrid strokeDasharray="3 3" vertical={false} stroke="#e2e8f0" />
                <XAxis dataKey="name" stroke="#64748b" fontSize={10} />
                <YAxis stroke="#64748b" />
                <Tooltip 
                  cursor={{fill: 'transparent'}}
                  contentStyle={{ borderRadius: '12px', border: 'none', boxShadow: '0 10px 15px -3px rgba(0,0,0,0.1)' }}
                />
                <Bar dataKey="value" radius={[4, 4, 0, 0]}>
                  {barData.map((entry, index) => (
                    <Cell key={`cell-${index}`} fill={EMOTION_COLORS[entry.name.toLowerCase()] || '#3b82f6'} />
                  ))}
                </Bar>
              </BarChart>
            </ResponsiveContainer>
          </div>
        </div>
      </div>
    </div>
  );
};
