import React, { useState } from 'react';
import './App.css';

interface PredictionResult {
  risk: string;
  score: number;
  emotion: string;
  keywords: string[];
  response: string;
  ai_generated_response: string;
  resources: string;
}

function App() {
  const [text, setText] = useState('');
  const [loading, setLoading] = useState(false);
  const [result, setResult] = useState<PredictionResult | null>(null);
  const [error, setError] = useState<string | null>(null);

  const API_URL = import.meta.env.VITE_API_URL || 'http://localhost:8001/api/v1/predict/';

  const handleSubmit = async (e: React.FormEvent) => {
    e.preventDefault();
    if (!text.trim()) {
      setError('Please enter your thoughts before submitting.');
      return;
    }

    setLoading(true);
    setError(null);
    setResult(null);

    try {
      const response = await fetch(API_URL, {
        method: 'POST',
        headers: { 'Content-Type': 'application/json' },
        body: JSON.stringify({ text }),
      });

      if (!response.ok) throw new Error(`API Error: ${response.status}`);
      const data = await response.json();
      setResult(data);
    } catch (err: any) {
      setError(err.message || 'An unexpected error occurred. Is the backend running?');
    } finally {
      setLoading(false);
    }
  };

  const getRiskColor = (risk: string) => {
    const r = risk.toLowerCase();
    if (r === 'low') return 'risk-low';
    if (r === 'medium') return 'risk-medium';
    if (r === 'high') return 'risk-high';
    return 'risk-default';
  };

  const getEmotionEmoji = (emotion: string) => {
    const emojis: { [key: string]: string } = {
      joy: '😊', sadness: '😢', fear: '😨', anger: '😠', surprise: '😲', love: '❤️',
    };
    return emojis[emotion.toLowerCase()] || '🤔';
  };

  return (
    <div className="app-container">
      <header className="header">
        <h1>💙 Mental Health AI Support</h1>
        <p>Advanced Hybrid Intelligence: specialized classifiers + generative LLM</p>
      </header>

      <main className="main-content">
        <form className="input-section" onSubmit={handleSubmit}>
          <textarea
            value={text}
            onChange={(e) => setText(e.target.value)}
            placeholder="How are you feeling? Type here..."
            rows={5}
            className={error && !text.trim() ? 'error-border' : ''}
          />
          <button type="submit" disabled={loading} className="submit-btn">
            {loading ? <span className="spinner"></span> : 'Get Deep AI Support'}
          </button>
        </form>

        {error && <div className="error-message">{error}</div>}

        {result && (
          <div className="results-section fade-in">
            <div className="results-grid">
              <div className="result-card">
                <h3>Risk Level</h3>
                <div className={`risk-badge ${getRiskColor(result.risk)}`}>{result.risk.toUpperCase()}</div>
                <p className="confidence">Hybrid Confidence: {(result.score * 100).toFixed(0)}%</p>
              </div>
              <div className="result-card">
                <h3>Detected Emotion</h3>
                <div className="emotion-badge">
                  <span className="emoji">{getEmotionEmoji(result.emotion)}</span>
                  <span className="emotion-text">{result.emotion.toUpperCase()}</span>
                </div>
              </div>
            </div>

            <div className="support-message ai-gen">
              <h3>✨ AI-Generated Personal Support</h3>
              <p className="gen-text">{result.ai_generated_response}</p>
              <div className="gen-footer">Generated by FLAN-T5-Base LLM for context-aware support.</div>
            </div>

            <div className="results-grid">
              <div className="result-card full-width">
                <h3>Detected Keywords & Insights</h3>
                {result.keywords.length > 0 ? (
                  <div className="keywords-container">
                    {result.keywords.map((kw, i) => (
                      <span key={i} className="keyword-tag">{kw}</span>
                    ))}
                  </div>
                ) : <p>None detected.</p>}
              </div>
            </div>

            <div className="support-message">
              <h3>Safety Guidelines</h3>
              <p>{result.response}</p>
            </div>

            {result.resources && (
              <div className="crisis-resources">
                <h3>⚠️ Immediate Support Resources</h3>
                <div dangerouslySetInnerHTML={{ __html: result.resources.replace(/\n/g, '<br/>') }} />
              </div>
            )}
          </div>
        )}
      </main>

      <footer className="footer">
        <p><strong>Disclaimer:</strong> This tool is for informational purposes only. It is not medical advice.</p>
      </footer>
    </div>
  );
}

export default App;
